[package]
name = "sbae-policy"
description = "Token authentication and policy evaluation for secretbae."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true

[dependencies]
sbae-proto.workspace    = true
data-encoding.workspace = true
getrandom.workspace     = true
sha2.workspace          = true
subtle.workspace        = true
zeroize.workspace       = true
serde.workspace         = true
serde_json.workspace    = true
thiserror.workspace     = true
time.workspace          = true
uuid.workspace          = true

[lints]
workspace = true
