#!/bin/sh
set -e

case "$1" in
remove | deconfigure)
    if command -v systemctl >/dev/null 2>&1; then
        systemctl stop secretbaed >/dev/null 2>&1 || true
        systemctl disable secretbaed >/dev/null 2>&1 || true
    fi
    ;;
esac

exit 0
