# System user and group definition for secretbae daemon
# Type Name      ID  GECOS                        Home directory      Shell
u      secretbae -   "secretbae daemon service"   /var/lib/secretbae  /usr/sbin/nologin
